### ISSUE TITLE
ImportError when using Python 3

### ISSUE THREAD

**Issue by githubnemo** [mcf06/theano_ctc#3]
I get the following error after installing `theano_ctc` using the setup script using Python 3:

```
>>> import theano_ctc 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'theano_ctc'
```

This is probably due to the way you import `ctc_base`, e.g.:

```
from ctc_base import CtcBase
```

which should really be a (package-)relative import:

```
from .ctc_base import CtcBase
```

This should also fail for python 2.x when using the 

```
from __future__ import absolute_import
```

import statement.

**Comment by mcf06** [comment]
I've updated the ctc_base imports to be relative. I don't have python3 set up, though I tried doing "from **future** import absolute_import" before importing theano_ctc and it worked on python2 (with or without the relative import change). Let me know if this works for you. Thanks!

**Comment by githubnemo** [comment]
Looks good, thanks!

When writing future proof python code you should use [these](http://python-future.org/imports.html) imports:

```
from __future__ import absolute_import, division, print_function
```

Basically making `x//y` return integers, enforce python3 imports and providing `print(x)` instead of `print x`.
