### ISSUE TITLE
What is the shape of input?

### ISSUE THREAD

**Issue by ghost** [mcf06/theano_ctc#6]
@mcf06 :  As of the definition of ctc_cost 

`def ctc_cost(acts, labels, input_lengths=None)`

What's the exact shape of 'acts' , 'lables' and 'input_lenghts' ? 

And, if input samples are of different lengths, how should 'acts' be padded? pre or post?

**Comment by mcf06** [comment]
I've added a few paragraphs of documentation to this function (see theano_ctc/**init**.py). Let me know if something is unclear. Also, check out the tests for some simple, working examples.
