### ISSUE TITLE
Wrapper behavior for negative labels is undocumented

### ISSUE THREAD

**Issue by githubnemo** [mcf06/theano_ctc#7]
I am missing a hint that the label sizes are computed by the wrapper and that negative values are designated as padding values by this wrapper. Did I just overlook the place where this is documented?

On a side note: shouldn't be the label 0 be ignored as well since it is reserved for 'blank'?

**Comment by mcf06** [comment]
I've added a few paragraphs of documentation to the main ctc_loss function (see theano_ctc/init.py). Let me know if something is unclear. 

Perhaps label 0 should be ignored. Perhaps it should throw an exception, since its presence might indicate other problems with the labels.

**Comment by githubnemo** [comment]
Thanks, the documentation looks good. I think would also be helpful if it stated that warp-ctc does the softmax. This might be clear to anyone who knows warp-ctc but is not for someone who is just interested in CTC and simply uses this wrapper to get it.

+1 for exception as it is an error case (according to the documentation).
