### ISSUE TITLE
Operations on gradients are ignored

### ISSUE THREAD

**Issue by githubnemo** [mcf06/theano_ctc#9]
Related: https://github.com/sherjilozair/ctc/issues/2
Test file: https://github.com/githubnemo/theano_ctc/blob/gradients/tests/test_ctc_gradients.py

Any computation on the gradient of the CTC loss is ignored:

```
tGrad = T.grad(T.mean(tCost), tsActs)
tGrad2x = T.grad(2 * T.mean(tCost), tsActs)
```

Both operations will yield the same result.

**Comment by mcf06** [comment]
Good catch, thanks. Fixed.
